Double/Triple bracket matching
Frederisk/Wikitext-VSCode-Extension pull request #45
Opened 2021-12-17 18:51 UTC by Anduh

- Bracket identification: wikitext templates (`{{ }}`), template parameters (`{{{ }}}`) are separatly identified from `{ }`, and will be grouped together when selected
- if `editor.bracketPairColorization.enabled` is used, highlights make sense

**Before**
![vscode-wikitext-before](https://user-images.githubusercontent.com/2890634/146592151-a89cda1f-6c1b-4176-96db-0d4782d2515f.png)

**After**
![vscode-wikitext-after](https://user-images.githubusercontent.com/2890634/146592183-90f6eb2d-bfc3-4b0f-b594-3499387f76eb.png)

## Other
- my `yarn.lock` & `package-lock.json` had bunch of changes, but excluded them as irrelevant

2021-12-18 14:00 UTC, Frederisk requested changes
The is also a part of `tmLanguage` file that needs to be modified, this part may be completed by me.

2021-12-18 17:37 UTC, Anduh commented on language-configuration.yaml
>      - "}"
> should `{}` be deleted?

Kinda feel it should, not aware of actual use of it. If we remove it, we need to add double/triple to the auto-closing part

2021-12-19 07:13 UTC, Frederisk commented on language-configuration.yaml
>      - "}"
Delete it, this is how the brackets worked in the past.

2021-12-25 10:56 UTC, Frederisk commented
@Anduh, Is there any progress on the change requested?

2021-12-25 15:24 UTC, Anduh commented
Oh right, I tested additional changes some day ago, but also ended up adding a bunch of snippets, just didn't clean up things to submit as separate PR yet.

I'll update this PR by tomorrow.

2022-01-22 18:30 UTC, Frederisk commented
Continue #52.

2022-01-22 18:40 UTC, closed without merging